# ***Pytorch Practice***

In [27]:
import torch

In [ ]:
torch.tensor(2)

tensor(2)

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.zeros(93)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
torch.rand(5)

tensor([0.7726, 0.4442, 0.5262, 0.0096, 0.8282])

In [ ]:
torch.rand((2,2))

tensor([[0.8198, 0.8161],
        [0.7878, 0.4645]])

In [ ]:
torch.randn((5,5))

tensor([[-0.3118,  1.2864, -0.0601,  0.2492,  0.7290],
        [ 1.8787, -1.2882,  1.1359,  0.1237,  0.0101],
        [ 1.1216, -1.0845, -0.1381,  1.0926,  0.0491],
        [-0.6080, -0.5077, -0.8302, -1.1316,  0.4332],
        [ 0.0266, -1.1289, -1.6785, -0.7189, -0.2613]])

In [ ]:
torch.arange(0,10,0.01)

tensor([0.0000, 0.0100, 0.0200, 0.0300, 0.0400, 0.0500, 0.0600, 0.0700, 0.0800,
        0.0900, 0.1000, 0.1100, 0.1200, 0.1300, 0.1400, 0.1500, 0.1600, 0.1700,
        0.1800, 0.1900, 0.2000, 0.2100, 0.2200, 0.2300, 0.2400, 0.2500, 0.2600,
        0.2700, 0.2800, 0.2900, 0.3000, 0.3100, 0.3200, 0.3300, 0.3400, 0.3500,
        0.3600, 0.3700, 0.3800, 0.3900, 0.4000, 0.4100, 0.4200, 0.4300, 0.4400,
        0.4500, 0.4600, 0.4700, 0.4800, 0.4900, 0.5000, 0.5100, 0.5200, 0.5300,
        0.5400, 0.5500, 0.5600, 0.5700, 0.5800, 0.5900, 0.6000, 0.6100, 0.6200,
        0.6300, 0.6400, 0.6500, 0.6600, 0.6700, 0.6800, 0.6900, 0.7000, 0.7100,
        0.7200, 0.7300, 0.7400, 0.7500, 0.7600, 0.7700, 0.7800, 0.7900, 0.8000,
        0.8100, 0.8200, 0.8300, 0.8400, 0.8500, 0.8600, 0.8700, 0.8800, 0.8900,
        0.9000, 0.9100, 0.9200, 0.9300, 0.9400, 0.9500, 0.9600, 0.9700, 0.9800,
        0.9900, 1.0000, 1.0100, 1.0200, 1.0300, 1.0400, 1.0500, 1.0600, 1.0700,
        1.0800, 1.0900, 1.1000, 1.1100, 

In [ ]:
torch.cuda.is_available()

False

In [ ]:
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [ ]:
a =torch.arange(6).reshape(3,2)

In [ ]:
a.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
x = torch.tensor(2.0, requires_grad=True)   # for gradiant traking
y = x ** 3 + 2 * x

print(y.backward())   # remember backprop(backwards fn) only works with scalar values
print(x.grad)

x.detach()  # to stop tracking gradients

None
tensor(14.)


In [ ]:
x = torch.tensor([1,2,3,4] , requires_grad = True , dtype = torch.float32)
print(x.requires_grad)

True


In [ ]:
x = torch.tensor(2.0, requires_grad=True)

with torch.no_grad():
  y = x ** 3 + 2 * x

print(y.requires_grad)

False


In [ ]:
torch.rand(3)   # uniform distribution

tensor([0.2566, 0.7936, 0.9408])

In [ ]:
torch.manual_seed(42)
torch.rand(3)

tensor([0.8823, 0.9150, 0.3829])

In [ ]:
torch.manual_seed(42)  # seed use for reproduce same random numbers
torch.rand(3)

tensor([0.8823, 0.9150, 0.3829])

In [ ]:
torch.randn(3)   # Gussian Distribution

tensor([ 0.3623, -0.1671, -0.1079])

In [ ]:
torch.empty(2,3)

tensor([[7.1450e+31, 6.1970e-04, 2.8909e+26],
        [1.3672e-40, 9.1837e-41, 4.1478e-43]])

In [ ]:
x = torch.linspace(0, 1, 5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [ ]:
torch.eye(3)   # identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
print("using full ->", torch.full((3, 3), 5))

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
a = torch.tensor([1,2,3,4,5,6])   # reshaping tensor  without coping
a.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat((x, y), dim=1)
print(z)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [ ]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = torch.stack((x, y), dim=0)
print(z)

tensor([[1, 2],
        [3, 4]])


In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = a
print(id(a))
print(id(b))


134855373323424
134855373323424


In [ ]:
a = torch.tensor([[1, 2, 3000], [4, 5, 699999999]])     #  prevent value from going to high and to low
torch.clamp(a , min = 3 , max = 6)


tensor([[3, 3, 6],
        [4, 5, 6]])

In [ ]:
a[0][0] = 10
print(a)
print(b)

tensor([[10,  2,  3],
        [ 4,  5,  6]])
tensor([[10,  2,  3],
        [ 4,  5,  6]])


In [ ]:
b = a.clone()   # different location
print(id(a))
print(id(b))

134855373323424
134855060627904


In [ ]:
x = torch.device('cude' if torch.cuda.is_available() else 'cpu')
a = torch.tensor([1,2,3,4,5,6] , device=x )
print(a.device)

cpu


**nn.Module**

In [ ]:
# nn.linear

import torch.nn as nn

layer = nn.Linear(in_features=10, out_features=5 , bias = True)
layer

Linear(in_features=10, out_features=5, bias=True)

In [ ]:
layer.weight.shape

torch.Size([5, 10])

In [ ]:
layer.weight

Parameter containing:
tensor([[ 0.2905, -0.0693,  0.0638, -0.1540,  0.1857,  0.2788, -0.2320,  0.2749,
          0.0592,  0.2336],
        [ 0.0428,  0.1525, -0.0446,  0.2438,  0.0467, -0.1476,  0.0806, -0.1457,
         -0.0371, -0.1284],
        [ 0.2098, -0.2496, -0.1458, -0.0893, -0.1901,  0.0298, -0.3123,  0.2856,
         -0.2686,  0.2441],
        [ 0.0526, -0.1027,  0.1954,  0.0493,  0.2555,  0.0346, -0.0997,  0.0850,
         -0.0858,  0.1331],
        [ 0.2823,  0.1828, -0.1382,  0.1825,  0.0566,  0.1606, -0.1927, -0.3130,
         -0.1222, -0.2426]], requires_grad=True)

In [ ]:
layer.bias

Parameter containing:
tensor([ 0.2595,  0.0911,  0.1310,  0.1000, -0.0055], requires_grad=True)

In [ ]:
x = nn.LazyLinear(out_features=6)  # LazyLinear doesn't require any in-features


In [ ]:
a = torch.rand(3,10)
y = x(a)
y

tensor([[ 0.1547, -0.8509, -0.1830, -0.8295,  0.0347, -0.0427],
        [ 0.3711, -0.8877, -0.2340, -0.8023, -0.2234, -0.0778],
        [ 0.2801, -0.7622, -0.1559, -0.7509, -0.5300, -0.0039]],
       grad_fn=<AddmmBackward0>)

In [ ]:
nn.Bilinear(in1_features=3, in2_features=4, out_features=5).weight  # bilinear can  take multiple inputs features

Parameter containing:
tensor([[[ 0.5480,  0.1519,  0.3871,  0.5692],
         [-0.0885,  0.1198, -0.4013, -0.1190],
         [ 0.4276,  0.2960, -0.3653, -0.4630]],

        [[-0.3945, -0.5698, -0.4455, -0.1428],
         [ 0.3896,  0.0966, -0.4391, -0.4632],
         [ 0.2872, -0.4295, -0.0711,  0.2770]],

        [[-0.2672, -0.0630, -0.0503, -0.1366],
         [-0.2927, -0.5147, -0.4667, -0.3091],
         [ 0.5576, -0.2789, -0.3877,  0.1399]],

        [[ 0.1591,  0.3163,  0.4389,  0.3215],
         [-0.5724,  0.0512,  0.3497, -0.0534],
         [-0.3402,  0.5504, -0.2159, -0.3287]],

        [[-0.5205,  0.0258,  0.2558,  0.1278],
         [ 0.1142, -0.4379, -0.5392,  0.0102],
         [ 0.5264,  0.3331, -0.3362, -0.0749]]], requires_grad=True)

# **ANN in pytorch**

In [28]:
class ANNmodel(nn.Module):
  def __init__(self, inputs):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(inputs , 8),
        nn.ReLU(),
        nn.Linear(8,1),
        nn.Sigmoid()
    )

  def forward(self , inputs):
    result = self.network(inputs)
    return result

In [31]:
import torch.optim as optim

model = ANNmodel(inputs=5)
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)


features = torch.rand(10, 5)
targets = torch.randint(0, 2, (10, 1), dtype=torch.float32)


model.train()
for epoch in range(20):
    optimizer.zero_grad()
    outputs = model(features)
    loss = criterion(outputs, targets)
    loss.backward()  # Compute gradients
    optimizer.step()  # Update weights
    print(f"Epoch {epoch+1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.6986993551254272
Epoch 2, Loss: 0.6986433267593384
Epoch 3, Loss: 0.6985875368118286
Epoch 4, Loss: 0.6985318064689636
Epoch 5, Loss: 0.6984761953353882
Epoch 6, Loss: 0.6984208822250366
Epoch 7, Loss: 0.6983655691146851
Epoch 8, Loss: 0.6983104944229126
Epoch 9, Loss: 0.6982554793357849
Epoch 10, Loss: 0.6982006430625916
Epoch 11, Loss: 0.6981459259986877
Epoch 12, Loss: 0.6980913877487183
Epoch 13, Loss: 0.6980369687080383
Epoch 14, Loss: 0.6979825496673584
Epoch 15, Loss: 0.6979284882545471
Epoch 16, Loss: 0.6978744268417358
Epoch 17, Loss: 0.6978204250335693
Epoch 18, Loss: 0.6977739334106445
Epoch 19, Loss: 0.6977487802505493
Epoch 20, Loss: 0.6977237462997437


Dataset and Dataloader

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self, data, targets):
    self.data = data
    self.targets = targets

  def __len__(self):
    return len(self.data)

  def __getitem__(self, index):
    sample = self.data[index]
    target = self.targets[index]
    return sample, target

In [ ]:
features =  torch.rand(10,5)
dataset = CustomDataset(data=features, targets=torch.rand(10,1))
loader = DataLoader(dataset, batch_size=3 , shuffle = True)

for data , target in loader:
  print("data: " , data)
  print("Target : " , target)

data:  tensor([[0.5307, 0.7196, 0.3496, 0.7583, 0.7315],
        [0.2733, 0.1318, 0.4000, 0.3789, 0.5643],
        [0.4749, 0.4467, 0.3005, 0.9074, 0.3522]])
Target :  tensor([[0.6801],
        [0.1164],
        [0.0232]])
data:  tensor([[0.0213, 0.8367, 0.7197, 0.8095, 0.4760],
        [0.8287, 0.7550, 0.0169, 0.8690, 0.1799],
        [0.2499, 0.4707, 0.2336, 0.5447, 0.1643]])
Target :  tensor([[0.0977],
        [0.8897],
        [0.8078]])
data:  tensor([[0.8348, 0.4765, 0.3717, 0.7824, 0.6314],
        [0.2720, 0.6550, 0.6079, 0.6978, 0.5279],
        [0.4794, 0.9396, 0.4089, 0.3736, 0.5389]])
Target :  tensor([[0.9700],
        [0.0794],
        [0.9364]])
data:  tensor([[0.7081, 0.1552, 0.2460, 0.8960, 0.1653]])
Target :  tensor([[0.8065]])


*AUTOGRAD*

In [ ]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
c = a * b + b**2
c.backward()
print("dc/da:", a.grad)
print("dc/db:", b.grad)

dc/da: tensor(3.)
dc/db: tensor(8.)


# **CNN**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

model = nn.Sequential(
    nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.BatchNorm2d(32),
    nn.MaxPool2d(2, 2),

    nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.BatchNorm2d(64),
    nn.MaxPool2d(2, 2),

    nn.Flatten(),
    nn.Linear(64*7*7, 128),
    nn.ReLU(),
    nn.Linear(128, 10)
)

print(model)

x = torch.randn(16, 1, 28, 28)
out = model(x)

print("Output shape:", out.shape)  # (16, 10)

Sequential(
  (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU()
  (2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (4): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (5): ReLU()
  (6): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (8): Flatten(start_dim=1, end_dim=-1)
  (9): Linear(in_features=3136, out_features=128, bias=True)
  (10): ReLU()
  (11): Linear(in_features=128, out_features=10, bias=True)
)
Output shape: torch.Size([16, 10])


# **RNN**

In [ ]:
import torch
import torch.nn as nn


x = torch.randn(2, 5, 10)


class SimpleRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers=1):
        super(SimpleRNN, self).__init__()
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, hidden = self.rnn(x)
        out = self.fc(out[:, -1, :])
        return out

model = SimpleRNN(input_size=10, hidden_size=20, output_size=2, num_layers=1)


y = model(x)
print(y.shape)

torch.Size([2, 2])
